//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myImage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_register
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_register()
        {
            this.tbl_order = new HashSet<tbl_order>();
        }
    
        public int cust_id { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public System.DateTime dob { get; set; }
        public string gender { get; set; }
        public long p_number { get; set; }
        public string address { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order> tbl_order { get; set; }
    }
}
